# Generated by Django 3.2.4 on 2021-06-23 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_person',
            old_name='lenguajes_domaine',
            new_name='programming_languages',
        ),
        migrations.AddField(
            model_name='about_person',
            name='category',
            field=models.CharField(default='Junior', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_person',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
